### ISSUE TITLE
Add TRLN/Institution Name to paging widget when single or no results

### ISSUE THREAD

**Issue by corylown** [trln/trln_argon#4]
This is in locales. Need to pass in the filter name to the locale.

Currently in trln_argon/config/locales/trln_argon.en.yml
```
        search:
            pagination_info:
                no_items_found: 'No %{entry_name} found'
                single_item_found: '<strong>1</strong> %{entry_name} found'
```
